export const SAMPLE_EVENTS = [
  {
    title: 'Football Tournament',
    organizer: 'Organizer_123!',
    date: 'Sep 15, 2023 (11:30 am - 02:30 pm)',
    location: 'Football Stadium, Lahug',
    numParticipants: 23,
    maxParticipants: 25,
  },
  {
    title: 'Football Match',
    organizer: 'User456#',
    date: 'Sep 20, 2023 (04:30 pm - 07:30 pm)',
    location: 'Football Field, Lapu-Lapu',
    numParticipants: 13,
    maxParticipants: 15,
  },
  {
    title: 'Football League',
    organizer: 'Organizer_XYZ@',
    date: 'Sep 25, 2023 (07:00 pm - 10:00 pm)',
    location: 'Football Stadium, Talisay',
    numParticipants: 21,
    maxParticipants: 0,
  },
  {
    title: 'Football Match',
    organizer: 'User123#',
    date: 'Sep 30, 2023 (01:00 pm - 04:00 pm)',
    location: 'Football Field, Cebu City',
    numParticipants: 9,
    maxParticipants: 10,
  },
  {
    title: 'Football Tournament',
    organizer: 'Organizer_456@',
    date: 'Oct 05, 2023 (03:30 pm - 06:30 pm)',
    location: 'Football Field, Mandaue',
    numParticipants: 26,
    maxParticipants: 30,
  },
  {
    title: 'Football Friendly',
    organizer: 'User789!',
    date: 'Oct 10, 2023 (09:00 am - 12:00 pm)',
    location: 'Football Pitch, Banilad',
    numParticipants: 18,
    maxParticipants: 0,
  },
  {
    title: 'Football Championship',
    organizer: 'Organizer_XYZ#',
    date: 'Oct 15, 2023 (01:30 pm - 04:30 pm)',
    location: 'Football Stadium, Talamban',
    numParticipants: 8,
    maxParticipants: 10,
  },
  {
    title: 'Football Showmatch',
    organizer: 'User_XYZ',
    date: 'Oct 20, 2023 (05:00 pm - 08:00 pm)',
    location: 'Football Ground, Mabolo',
    numParticipants: 16,
    maxParticipants: 18,
  },
  {
    title: 'Football Tournament',
    organizer: 'Organizer#123',
    date: 'Oct 25, 2023 (09:30 am - 12:30 pm)',
    location: 'Football Field, Guadalupe',
    numParticipants: 20,
    maxParticipants: 25,
  },
  {
    title: 'Football Friendly',
    organizer: 'User456@',
    date: 'Oct 30, 2023 (02:00 pm - 05:00 pm)',
    location: 'Football Field, Talisay',
    numParticipants: 12,
    maxParticipants: 0,
  },
  {
    title: 'Football League',
    organizer: 'Organizer_XYZ!',
    date: 'Nov 05, 2023 (06:00 pm - 09:00 pm)',
    location: 'Football Stadium, Lahug',
    numParticipants: 22,
    maxParticipants: 30,
  },
  {
    title: 'Football Match',
    organizer: 'User_123#',
    date: 'Nov 10, 2023 (10:30 am - 01:30 pm)',
    location: 'Football Field, Mandaue',
    numParticipants: 15,
    maxParticipants: 18,
  },
  {
    title: 'Football Tournament',
    organizer: 'Organizer_456@',
    date: 'Nov 15, 2023 (03:00 pm - 06:00 pm)',
    location: 'Football Field, Cebu City',
    numParticipants: 27,
    maxParticipants: 30,
  },
  {
    title: 'Football Friendly',
    organizer: 'User_XYZ@',
    date: 'Nov 20, 2023 (06:30 pm - 09:30 pm)',
    location: 'Football Pitch, Lapu-Lapu',
    numParticipants: 11,
    maxParticipants: 0,
  },
  {
    title: 'Football Championship',
    organizer: 'Organizer#789',
    date: 'Nov 25, 2023 (11:00 am - 02:00 pm)',
    location: 'Football Stadium, Talamban',
    numParticipants: 19,
    maxParticipants: 20,
  },
  {
    title: 'Football Showmatch',
    organizer: 'User123!',
    date: 'Nov 30, 2023 (02:30 pm - 05:30 pm)',
    location: 'Football Field, Guadalupe',
    numParticipants: 14,
    maxParticipants: 16,
  },
];
